config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    '/transactions/show',    to: 'transactions#show'
  post   '/transactions/search',  to: 'transactions#search'

  get    '/nfts',         to: 'nfts#index'
  get    '/nfts/new',     to: 'nfts#new'
  post   '/nfts/create',  to: 'nfts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nfts_controller.rb
class NftsController < ApplicationController
  require 'ipfs-api'

  skip_before_action :verify_authenticity_token

  def index
    @nfts = []
    listunspents = Glueby::Wallet.load(ENV['WALLET_ID']).internal_wallet.list_unspent
    listunspents.each do |listunspent|
      @nfts << listunspent if listunspent[:color_id]&.start_with?('c3')
    end
  end

  def new; end

  def create
    # write file
    upload_file = params[:upload_file]
    upload_dir = Rails.root.join('tmp', 'storage')
    upload_file_path = upload_dir + Time.now.to_i.to_s
    File.binwrite(upload_file_path, upload_file.read)

    # upload to ipfs
    ipfs = IPFS::Connection.new('http://ipfs:5001')
    ipfs.add File.new(upload_file_path) do |node|
      @cid = node.hash
    end

    # load wallet
    begin
      wallet = Glueby::Wallet.load(ENV['WALLET_ID'])
    rescue Glueby::Internal::Wallet::Errors::WalletNotFound
      flash.now[:danger] = 'Wallet not found. Are you run ./bin/rails ttms:init? Run it and restart server!'
      render 'new'
      return
    end

    # create token
    begin
      token = Glueby::Contract::Token.issue_nft_with_metadata(issuer: wallet, prefix: '', metadata: @cid)
    rescue Glueby::Contract::Errors::InsufficientFunds
      # deposit
      generateBlock(wallet)
      retry
    end
    generateBlock(wallet)

    flash[:success] = 'Success!'
    redirect_to transactions_show_path(txid: token[1].txid)
  end

  private

  def generateBlock(wallet)
    block = Glueby::Internal::RPC.client.generatetoaddress(1, wallet.internal_wallet.receive_address, ENV['AUTHORITY_KEY'])
    Rails.application.load_tasks
    Rake::Task['glueby:block_syncer:start'].execute
    Rake::Task['glueby:block_syncer:start'].clear
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def search
    txid = nil
    if params[:color_id].start_with?('c1', 'c2', 'c3')
      listunspents = Glueby::Wallet.load(ENV['WALLET_ID']).internal_wallet.list_unspent
      listunspents.each do |listunspent|
        txid = listunspent[:txid] if listunspent[:color_id] == params[:color_id]
      end
    else
      txid = params[:color_id]
    end

    redirect_to transactions_show_path(txid: txid)
  end

  def show
    txid = params[:txid]
    begin
      rawtransaction = Glueby::Internal::RPC.client.getrawtransaction(txid.to_s)
      @decodedtransaction = Glueby::Internal::RPC.client.decoderawtransaction(rawtransaction)
      @json = JSON.pretty_generate(@decodedtransaction)
    rescue
      flash[:danger] = 'No transactions found :('
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def decode_metadata(str_metadata)
    [str_metadata].pack('H*')
  end
end

app/views/layouts/_footer.html.slim
footer.footer
  div
    span
      | © 2022 
    = link_to "shmn7iii", "https://www.shmn7iii.net"

app/views/layouts/_header.html.slim
header.p-3.mb-3.border-bottom
  div.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
    = link_to "Tapyrus Token Metadata Sample", root_path, class: "d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none", id: "logo"
    ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
      li
        = link_to "NTF", nfts_path, class: "nav-link px-2 link-dark"
      li
        = link_to "Reissueble Token", "#", class: "nav-link px-2 link-secondary"
      li
        = link_to "Non-Reissueble Token", "#", class: "nav-link px-2 link-secondary"

    .searchBox
      = form_with(url: transactions_search_path) do |f|
        .d-flex
          = f.text_field :color_id, class: "form-control", required: "required", placeholder:"COLOR_ID or TxID"
          = f.submit "Search", class: "btn btn-outline-success mx-1"

    div.text-end
      a[href="https://github.com/shmn7iii/tapyrus_token_metadata_sample", class="nav-link px-2 link-dark"]
        svg[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"]
          path[d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Tapyrus Token Metadata Sample
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    = render 'layouts/header'
    .container.center
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
    = render 'layouts/footer'

app/views/nfts/index.html.slim
.tokens-header
  div
    h2 NFTs 
  div
    = link_to "Issue", nfts_new_path, class: "btn btn-outline-primary"
.tokens
  .card.card-body
    ul.list-group.list-group-flush
      - @nfts.each do |nft|
        li.list-group-item[style="text-align: left;"]
          p
            | COLOR_ID: #{nft[:color_id]}
          p
            | TxID: 
            = link_to "#{nft[:txid]}", transactions_show_path(txid: nft[:txid])

app/views/nfts/new.html.slim
h2
  | Create Tapyrus NFT with Metadata

div.card.card-body[style="max-width: 500px"]
  p[style="text-align: left;"]
    | Select Metadata file. File will be uploaded to IPFS.
  = form_with(url: 'create') do |f|
    .mb-3
      = f.file_field :upload_file, class: "form-control", required: "required"
    .center
      = f.submit "Issue token", class: "btn btn-outline-primary"

app/views/static_pages/home.html.slim
div.card.card-body
  h2.card-title
    | Sample of issuing token with metadata on Tapyrus 

  p.card-text[style="text-align: left;"]
    | Tapyrus でメタデータを付与したトークンを発行するサンプル。
    br
    | OP_RETURN の後ろに任意データを仕込んだスクリプトを持つアウトプットを発行トランザクションに捩じ込むことでオンチェーンでのメタデータ付与を実現した。また OP_RETURN の後ろに入れるデータも IPFS の CID にすることであらゆる容量、ファイル形式のデータを格納することが可能になっている。

  p.card-text[style="text-align: left;"]
    | 現在の対応トークンはNFTのみ。

  = link_to "Issue NFT now!", nfts_new_path, class: "btn btn-outline-primary"

app/views/transactions/show.html.slim
h2 Transaction Data

div.card[style="text-align: left;"]
  .card-header
    h5.card-title
      | TxInfo
    p.card-text
      | TxID: #{@decodedtransaction['txid']}
      br
      | Size: #{@decodedtransaction['size']}
  .card-body
    ul.list-group.list-group-flush
      - @decodedtransaction['vin'].each_with_index do |vin, n|
        li.list-group-item
          h5.card-title
            | TxIn[#{n}]

          - unless vin['coinbase'].nil?
            pre.card-text
              | This is coinbase transaction.
              br
              | Coinbase: "#{vin['coinbase']}"

          - else
            pre.card-text
              | TxID: 
              = link_to "#{vin['txid']}", transactions_show_path(txid: vin['txid'])
              br
              | vout: #{vin['vout']}

      - @decodedtransaction['vout'].each_with_index do |vout, n|
        li.list-group-item
          h5.card-title
            | TxOut[#{n}]

          - if vout['token'].start_with?('c1')
            pre.card-text
              | This is Reissuable Token.
          - elsif vout['token'].start_with?('c2')
            pre.card-text
              | This is Non-Reissuable Token.
          - elsif vout['token'].start_with?('c3')
            pre.card-text
              | This is NFT.

          - if vout['scriptPubKey']['asm'].start_with?('OP_RETURN')
            pre.card-text
              | This is Metadata output.
            pre.card-text
              | Metadata
              br
              - cid = decode_metadata(vout['scriptPubKey']['asm'].split()[1]).force_encoding("UTF-8")
              | 　IPFS CID: 
              = link_to "#{cid}", "localhost:8080/ipfs/#{cid}"
            pre.card-text
              | scriptPubkey
              br
              | 　asm: #{vout['scriptPubKey']['asm']}
              br
              | 　hex: #{vout['scriptPubKey']['hex']}
              br
              | 　type: #{vout['scriptPubKey']['type']}
          - else
            pre.card-text
              | Token: #{vout['token']}
              br
              | Value: #{vout['value']}

      li.list-group-item
        .text-end
          button[class="btn btn-outline-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"]
            | Show raw content
        .collapse#collapseExample
          .card.card-body
            pre
              = @json